export const SETPAGES = 'SET_PAGES';
export const SETPICKUPDATE = 'SET_PICKUP_DATE';
export const SETPICKUPLOCATION = 'SET_PICKUP_LOCATION';
export const SETSPECIALNEEDS = 'SET_SPECIAL_NEED';
export const SETBUTTONACTIVE = 'SET_BUTTON_ACTIVE';